# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PnwRotPyDialog
                                 A QGIS plugin
 Exploration of effect of NW rotation on YHS path
 Generated by Plugin Builder: https://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Steve White
        email                : stevewh@uw.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis._core import (QgsMessageLog,
                        Qgis,
                        QgsPoint,
                        QgsVectorLayer,
                        QgsFeature,
                        QgsGeometry,
                        QgsProject,
                        QgsCategorizedSymbolRenderer,
                        QgsRendererCategory,
                        QgsSymbol,
                        QgsWkbTypes)
from qgis.PyQt.QtGui import QColor, QCloseEvent # Bug - Qgis is fine with this import, PyCharm is not
from qgis.utils import iface
from .jdf_plate import JFP
from .rot_data import RotData
from .plate_motion import PlateMotion, PLoc, PDist
import test_utils as tu
from .geo_whiteboard import GeoWhiteboard
import euler_pole_regression as epr

# Important constants
NA_Speed = 23e-3    # m / yr (Current) = Adjusted to Owyhee=Humbolt cauldera ~14Ma 
NA_Bearing = 241.0  # degrees azimuth
YHS_lat = 44.43     # Yellowstone hotspot caldera
YHS_long = -110.67
Brothers_Lat = 47.652      # Mount Olympus
Brothers_Long = -123.141


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'pnw_rotation_py_dialog_base.ui'))

class PnwRotPyDialog(QtWidgets.QDialog, FORM_CLASS):
    name = 'PnwRotPyDialog'
    destRotDataLayerName = 'pnw rotation data'
    YHS_lat = 44.43
    YHS_lon = -110.67
    destYhsLayerName = 'YHS movement'

    def __init__(self, parent=None):
        super(PnwRotPyDialog, self).__init__(parent)
        self.setupUi(self)

        self.rotData = RotData()
        self.rotDisplayLayerSetup = False
        self.rotDestLayer = None
        self.yhsDestLayerSetup = False
        self.yhsDestLayer = None
        self.interpFunction = "LinearNDInterpolator"
        self.yhsPoints = [] # NA + Block YHS plot
        self.yhsOccludedPoints = [] # occluded by JdF
        self.naPoints = []  # NA only YHS plot
        self.yhsRotFeatureList = []
        self.plateMotion = PlateMotion()
        self.geoWhiteboard = None
        
        self.clearDataButton.clicked.connect(self.clearData)
        self.runYhsDataButton.clicked.connect(self.runYhsButtonClicked)
        self.rbYHS.toggled.connect(self.setStartPoint)
        self.rbBrothers.toggled.connect(self.setStartPoint)
        self.rbME.toggled.connect(self.setStartPoint)
        self.rbDisplayRot.clicked.connect(self.displayRotData)
        #self.rbShowJdFOcclusion.connect(self.showJdFOcclusion)

        self.clearData()
        self.setStartPoint()
        self.spbNaPlateBearing.setValue(NA_Bearing)
        self.spbNaPlateSpeed.setValue(NA_Speed)
        self.rotData.load()
        self.setupRotDisplayLayer()

        return

    def clearData(self):
        self.yhsPoints = []
        self.naPoints = []
        self.yhsOccludedPoints = []
        self.yhsRotFeatureList = []
        self.closeYhsLayer()
        self.closeRotLayer()
        return

    ####
    # Display Rotation Data
    ####
    def rbApplyRotationVClicked(self):

        if not self.setupRotDisplayLayer():
            QgsMessageLog.logMessage('failed to setup display rotation layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        self.displayRotData()
        return True

    def setupRotDisplayLayer(self):
        if self.rotDisplayLayerSetup:
            return True

        if not self.rotData.rotDataLoaded:
            QgsMessageLog.logMessage('failed to load rotation data from layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        providerName = 'memory'
        uri = 'Point?crs=epsg:4326'
        if self.rotDestLayer is None:
            self.rotDestLayer = QgsVectorLayer(uri, PnwRotPyDialog.destRotDataLayerName, providerName)

        if not self.rotDestLayer.isValid():
            QgsMessageLog.logMessage("Couldn't create rotDestLayer", tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        self.geoWhiteboard = GeoWhiteboard(self.rotDestLayer)
        
        #Copy over symbology from rot data layer
        sourceRenderer = self.rotData.rotSourceLayer.renderer()
        if not sourceRenderer is None:
            clonedRenderer = sourceRenderer.clone()
            if not clonedRenderer is None:
                self.rotDestLayer.setRenderer(clonedRenderer)

        #Copy rot data fields over too
        if self.rotDestLayer.dataProvider().addAttributes(self.rotData.rotFieldList):
            self.rotDestLayer.updateFields()
        else:
            QgsMessageLog.logMessage('failed to copy rot data', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        self.rotDisplayLayerSetup = True
        return True
    
    # def test_against_pnw_GPS_data():
    #     euler_pole = {"lat" : 45.0,  "long" : -90, "omega" : 1.23 }
    #     center_lat = 45.0
    #     center_long = -118
    #     max_distance = 350000 # m
    #     sample_lats, sample_lons, sample_v_east, sample_v_north = tb.get_GPS_rotation_data(center_lat, center_long, max_distance)

    #     #pole_result = epr.fit_euler_pole_linear(sample_lats, sample_lons, sample_v_east, sample_v_north)
    #     x = gn.solve_gauss_newton_2D_transform_geo(sample_lons, sample_lats, sample_v_east, sample_v_north, euler_pole)
    #     gn.print_x(x)
    #     #ek.print_result ("test_GPS_pole_extraction", pole_result)

    def displayRotData(self):
        # get gps data within 500 km
        lat_list, long_list, ve_list, vn_list =\
              tu.get_GPS_rotation_data(tu.OC_NA_Pole['lat'], tu.OC_NA_Pole['long'], 500000)
        for i in range(len(lat_list)):
            d_scaling = 0.001
            feature = self.rotData.createRotFeature(
                PLoc(long_list[i], lat_list[i]), PDist(ve_list[i], vn_list[i]), d_scaling)
            self.yhsRotFeatureList.append(feature)

        # get euler pole and display
        pole = epr.fit_euler_pole_linear(lat_list, long_list, ve_list, vn_list)
        label_text = f"{pole['long']:.4f}, {pole['lat']:.4f}, {pole['omega']:.4f} deg"
        self.geoWhiteboard.draw_target(pole['long'], pole['lat'], label_text)

        if not self.rotDisplayLayerSetup:
            self.setupRotDisplayLayer()
        if self.rbDisplayRot.isChecked():
            self.rotDestLayer.dataProvider().addFeatures(self.yhsRotFeatureList)
        else:
            self.rotDestLayer.dataProvider().truncate()
        QgsProject.instance().addMapLayer(self.rotDestLayer)
        self.rotDestLayer.triggerRepaint()

    ####
    # run Yhs Button
    ####

    def runYhsButtonClicked(self):
        if not self.setupYhsLayer() :
            QgsMessageLog.logMessage('failed to setup display rotation layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return

        # plugin_dir_os = os.path.dirname(os.path.realpath(__file__)) # point to plugin dir
        # file_path = os.path.join(plugin_dir_os, "rotation_run.csv")
        # with open(file_path, "w") as dataFile:
        startT = float(self.sbStartMa.value()) * 1e6
        if len(self.yhsPoints) == 0:
            self.rotData.setupSampling(self.interpFunction)
            self.plateMotion.initialize(startT, self.spbStartLatDD.value(), self.spbStartLongDD.value(),
                                self.spbNaPlateSpeed.value(), self.spbNaPlateBearing.value(), self.interpFunction, dataFile)
            startPoint = QgsPoint(self.spbStartLongDD.value(), self.spbStartLatDD.value())
            self.yhsPoints.append(startPoint)  # Set initial points
            self.naPoints.append(startPoint)

        for i in range (self.sbSteps.value()):
            deltaT = self.spbStepMa.value() * 1e6
            locYhs = self.plateMotion.getNextState(deltaT,  self.rotData,
                                self.rbApplyMaScaling.isChecked(),
                                self.rbGpsModel.isChecked())
            if not locYhs:
                print("Something went wrong. No update to track")
                break

            self.yhsPoints.append(QgsPoint(locYhs.long, locYhs.lat))

            if (locYhs.long < JFP.leadingEdgeLongitude(self.plateMotion.currentYr)
                    and self.rbShowJdFOcclusion.isChecked()):
                self.yhsOccludedPoints.append(QgsPoint(locYhs.long, locYhs.lat))

            if self.rbShowNA.isChecked():
                self.naPoints.append(QgsPoint(self.plateMotion.locNa.long, self.plateMotion.locNa.lat))

            # feature = self.rotData.createRotFeature(locYhs, self.plateMotion.distRot, 200.0 / -deltaT)
            # self.yhsRotFeatureList.append(feature)

        self.displayYhsData()
        if self.rbDisplayRot.isChecked():
            self.displayRotData()
        return

    def setupYhsLayer(self) :    # Rot layer must be loaded in qgism first(so not at qgis launch)
        if self.yhsDestLayerSetup:
            return True
        if self.yhsDestLayer is None:
            layer_name = 'YHS Track'
            uri = f"LineString?crs=epsg:4326&field=category_id:int&field=name:string"
            self.yhsDestLayer  = QgsVectorLayer(uri, layer_name, 'memory')

        if not self.yhsDestLayer.isValid():
            QgsMessageLog.logMessage("Could not instantiate plugin target layer", tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        categories = []
        # Category for ID 1 (Red)
        symbol1 = QgsSymbol.defaultSymbol(QgsWkbTypes.LineGeometry)
        symbol1.setColor(QColor("red"))
        symbol1.setWidth(0.5)
        category1 = QgsRendererCategory(1, symbol1, 'NA+Block YHS')
        categories.append(category1)

        # Category for ID 2 (Black)
        symbol2 = QgsSymbol.defaultSymbol(QgsWkbTypes.LineGeometry)
        symbol2.setColor(QColor("black"))
        symbol2.setWidth(0.5)
        category2 = QgsRendererCategory(2, symbol2, 'NA+Block YHS Occluded')
        categories.append(category2)

        # Category for ID 3 (Blue)
        symbol3 = QgsSymbol.defaultSymbol(QgsWkbTypes.LineGeometry)
        symbol3.setColor(QColor("blue"))
        symbol3.setWidth(0.5)
        category3 = QgsRendererCategory(3, symbol3, 'NA only YHS')
        categories.append(category3)

        renderer = QgsCategorizedSymbolRenderer('category_id', categories)
        self.yhsDestLayer.setRenderer(renderer)
        self.yhsDestLayerSetup = True
        return True

    def displayYhsData(self):
        #copy yhs data over
        feature1 = QgsFeature(self.yhsDestLayer.fields())
        feature1.setGeometry(QgsGeometry.fromPolyline(self.yhsPoints))
        feature1.setAttributes([1, 'NA+Block YHS'])

        feature2 = QgsFeature(self.yhsDestLayer.fields())
        feature2.setGeometry(QgsGeometry.fromPolyline(self.yhsOccludedPoints))
        feature2.setAttributes([2, 'NA+Block YHS Occluded'])

        feature3 = QgsFeature(self.yhsDestLayer.fields())
        feature3.setGeometry(QgsGeometry.fromPolyline(self.naPoints))
        feature3.setAttributes([3, 'NA Only YHS'])

        # Add feature to layer
        self.yhsDestLayer.startEditing()
        self.yhsDestLayer.addFeatures([feature1, feature2, feature3])
        #self.yhsDestLayer.addFeatures([feature3])

        self.yhsDestLayer.commitChanges()
        QgsProject.instance().addMapLayer(self.yhsDestLayer)

        self.yhsDestLayer.triggerRepaint()
        return True

    def setStartPoint(self):
        if  self.rbYHS.isChecked():
            self.spbStartLatDD.setValue(YHS_lat)
            self.spbStartLongDD.setValue(YHS_long)
        elif self.rbBrothers.isChecked():
            self.spbStartLatDD.setValue(Brothers_Lat)
            self.spbStartLongDD.setValue(Brothers_Long)
        return

    def removeLayer(self, layer):
        if layer :
            root = QgsProject.instance().layerTreeRoot()
            layer_node = root.findLayer(layer.id())
            if layer_node:
                layer_node.setItemVisibilityChecked(False)  # Set the checkbox to unchecked
                QgsProject.instance().removeMapLayers([layer.id()])
                iface.mapCanvas().refresh()
        return

    def closeRotLayer(self):
        if self.rotDestLayer:
            self.geoWhiteboard.erase_everything()
            self.removeLayer(self.rotDestLayer)
            self.rotDestLayer = None
            self.rotDisplayLayerSetup = False
        return

    def closeYhsLayer(self):
        if self.yhsDestLayer:
            self.removeLayer(self.yhsDestLayer)
            self.yhsDestLayer = None
            self.yhsDestLayerSetup = False
        return

    def closeEvent(self, event: QCloseEvent):
        self.closeRotLayer()
        self.closeYhsLayer()
        self.clearData()
        return

