# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PnwRotPyDialog
                                 A QGIS plugin
 Exploration of effect of NW rotation on YHS path
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Steve White
        email                : stevewh@uw.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis._core import (QgsMessageLog,
                        Qgis,
                        QgsPoint,
                        QgsVectorLayer,
                        QgsFeature,
                        QgsGeometry,
                        QgsProject,
                        QgsCategorizedSymbolRenderer,
                        QgsRendererCategory,
                        QgsSymbol,
                        QgsWkbTypes)
from qgis.PyQt.QtGui import QColor, QCloseEvent # Bug - Qgis is fine with this import, PyCharm is not
from qgis.utils import iface

from .rot_data import RotData
from .plate_motion import PlateMotion, PState

# Important constants
NA_Speed = 38e-3    # m / yr (Current) = Adjusted to Owyhee=Humbolt cauldera ~14Ma 
NA_Bearing = 241.0  # degrees azimuth
YHS_lat = 44.43     # Yellowstone hotspot caldera
YHS_long = -110.67
Brothers_Lat = 47.652      # Mount Olympus
Brothers_Long = -123.141

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'pnw_rotation_py_dialog_base.ui'))

class PnwRotPyDialog(QtWidgets.QDialog, FORM_CLASS):
    name = 'PnwRotPyDialog'
    destRotDataLayerName = 'pnw rotation data'
    YHS_lat = 44.43
    YHS_lon = -110.67
    destYhsLayerName = 'YHS movement'

    def __init__(self, parent=None):
        """Constructor."""
        super(PnwRotPyDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect

        self.setupUi(self)

        self.rotData = RotData()
        self.rotDisplayLayerSetup = False
        self.rotDestLayer = None
        self.yhsDestLayerSetup = False
        self.yhsDestLayer = None
        self.interpFunction = "LinearNDInterpolator"
        self.yhsPoints = [] # NA + Block YHS plot
        self.naPoints = []  # NA only YHS plot
        self.yhsRotFeatureList = []
        self.plateMotion = PlateMotion()
        
        self.clearDataButton.clicked.connect(self.clearData)
        self.runYhsDataButton.clicked.connect(self.runYhsButtonClicked)
        self.rbYHS.toggled.connect(self.setStartPoint)
        self.rbBrothers.toggled.connect(self.setStartPoint)
        self.rbME.toggled.connect(self.setStartPoint)
        self.rbDisplayRot.clicked.connect(self.displayRotData)

        self.clearData()
        self.setStartPoint()
        self.spbNaPlateBearing.setValue(NA_Bearing)
        self.spbNaPlateSpeed.setValue(NA_Speed)
        self.rotData.load()
        self.setupRotDisplayLayer()
        return

    def clearData(self):
        self.yhsPoints = []
        self.naPoints = []
        self.yhsRotFeatureList = []
        self.closeYhsLayer()
        self.closeRotLayer()
        return

    ####
    # Display Rotation Data
    ####
    def rbApplyRotationVClicked(self):

        if not self.setupRotDisplayLayer():
            QgsMessageLog.logMessage('failed to setup display rotation layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        self.displayRotData(self.rotData.rotFeatureList)
        return True

    def setupRotDisplayLayer(self):
        if self.rotDisplayLayerSetup:
            return True

        if not self.rotData.rotDataLoaded:
            QgsMessageLog.logMessage('failed to load rotation data from layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        providerName = 'memory'
        uri = 'Point?crs=epsg:4326'
        if self.rotDestLayer is None:
            self.rotDestLayer = QgsVectorLayer(uri, PnwRotPyDialog.destRotDataLayerName, providerName)

        if not self.rotDestLayer.isValid():
            QgsMessageLog.logMessage("Couldn't create rotDestLayer", tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        #Copy over symbology from rot data layer
        sourceRenderer = self.rotData.rotSourceLayer.renderer()
        if not sourceRenderer is None:
            clonedRenderer = sourceRenderer.clone()
            if not clonedRenderer is None:
                self.rotDestLayer.setRenderer(clonedRenderer)

        #Copy rot data fields over too
        if self.rotDestLayer.dataProvider().addAttributes(self.rotData.rotFieldList):
            self.rotDestLayer.updateFields()
        else:
            QgsMessageLog.logMessage('failed to copy rot data', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        self.rotDisplayLayerSetup = True
        return True

    def displayRotData(self):
        if self.rbApplyRotationV.isChecked():
            if not self.rotDisplayLayerSetup:
                self.setupRotDisplayLayer()
            if self.rbDisplayRot.isChecked():
                self.rotDestLayer.dataProvider().addFeatures(self.yhsRotFeatureList)
            else:
                self.rotDestLayer.dataProvider().truncate()
            QgsProject.instance().addMapLayer(self.rotDestLayer)
            self.rotDestLayer.triggerRepaint()

    ####
    # run Yhs Button
    ####

    def runYhsButtonClicked(self):
        if not self.setupYhsLayer() :
            QgsMessageLog.logMessage('failed to setup display rotation layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return

        dataFile = None
        plugin_dir_os = os.path.dirname(os.path.realpath(__file__)) # point to plugin dir
        file_path = os.path.join(plugin_dir_os, "rotation_run.csv")
        with open(file_path, "w") as dataFile:
            startT = float(self.sbStartMa.value()) * 1e6;
            if len(self.yhsPoints) == 0:
                self.rotData.setupSampling(self.interpFunction)
                self.plateMotion.initialize(startT, self.spbStartLatDD.value(), self.spbStartLongDD.value(),
                                    self.spbNaPlateSpeed.value(), self.spbNaPlateBearing.value(), self.interpFunction, dataFile)
                startPoint = QgsPoint(self.spbStartLongDD.value(), self.spbStartLatDD.value())
                self.yhsPoints.append(startPoint)  # Set initial points
                self.naPoints.append(startPoint)

            for i in range (self.sbSteps.value()):
                deltaT = self.spbStepMa.value() * 1e6;
                currentState = self.plateMotion.getNextState(deltaT,  self.rotData,
                                    self.rbApplyMaScaling.isChecked(), self.rbApplyRotationV.isChecked())
                if not currentState:
                    print("Something went wrong. No update to track")
                    break

                self.yhsPoints.append(QgsPoint(currentState.longitude, currentState.latitude))
                self.naPoints.append(QgsPoint(self.plateMotion.naState.longitude, self.plateMotion.naState.latitude))

                feature = self.rotData.createRotFeature(currentState, 200.0)
                self.yhsRotFeatureList.append(feature)

            self.displayYhsData()
            if self.rbDisplayRot.isChecked() and self.rbApplyRotationV.isChecked():
                self.displayRotData()
        return

    def setupYhsLayer(self) :    # Rot layer must be loaded in qgism first(so not at qgis launch)
        if self.yhsDestLayerSetup:
            return True
        if self.yhsDestLayer is None:
            layer_name = 'YHS Track'
            uri = f"LineString?crs=epsg:4326&field=category_id:int&field=name:string"
            self.yhsDestLayer  = QgsVectorLayer(uri, layer_name, 'memory')

        if not self.yhsDestLayer.isValid():
            QgsMessageLog.logMessage("Could not instantiate plugin target layer", tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        categories = []
        # Category for ID 1 (Red)
        symbol1 = QgsSymbol.defaultSymbol(QgsWkbTypes.LineGeometry)
        symbol1.setColor(QColor("red"))
        symbol1.setWidth(0.5)
        category1 = QgsRendererCategory(1, symbol1, 'NA+Block YHS (Red)')
        categories.append(category1)

        # Category for ID 2 (Blue)
        symbol2 = QgsSymbol.defaultSymbol(QgsWkbTypes.LineGeometry)
        symbol2.setColor(QColor("blue"))
        symbol2.setWidth(0.5)
        category2 = QgsRendererCategory(2, symbol2, 'NA only YHS (Blue)')
        categories.append(category2)

        renderer = QgsCategorizedSymbolRenderer('category_id', categories)
        self.yhsDestLayer.setRenderer(renderer)
        self.yhsDestLayerSetup = True
        return True

    def displayYhsData(self):

        #copy yhs data over
        feature1 = QgsFeature(self.yhsDestLayer.fields())
        feature1.setGeometry(QgsGeometry.fromPolyline(self.yhsPoints))
        feature1.setAttributes([1, 'NA+Block YHS'])

        feature2 = QgsFeature(self.yhsDestLayer.fields())
        feature2.setGeometry(QgsGeometry.fromPolyline(self.naPoints))
        feature2.setAttributes([2, 'NA YHS'])

        # Add feature to layer
        self.yhsDestLayer.startEditing()
        self.yhsDestLayer.addFeatures([feature1, feature2])
        self.yhsDestLayer.commitChanges()
        QgsProject.instance().addMapLayer(self.yhsDestLayer)

        self.yhsDestLayer.triggerRepaint()
        return True

    def setStartPoint(self):
        if  self.rbYHS.isChecked():
            self.spbStartLatDD.setValue(YHS_lat)
            self.spbStartLongDD.setValue(YHS_long)
        elif self.rbBrothers.isChecked():
            self.spbStartLatDD.setValue(Brothers_Lat)
            self.spbStartLongDD.setValue(Brothers_Long)
        return

    def removeLayer(self, layer):
        if layer :
            root = QgsProject.instance().layerTreeRoot()
            layer_node = root.findLayer(layer.id())
            if layer_node:
                layer_node.setItemVisibilityChecked(False)  # Set the checkbox to unchecked
                QgsProject.instance().removeMapLayers([layer.id()])
                iface.mapCanvas().refresh()
        return

    def closeRotLayer(self):
        if self.rotDestLayer:
            self.removeLayer(self.rotDestLayer)
            self.rotDestLayer = None
            self.rotDisplayLayerSetup = False
        return

    def closeYhsLayer(self):
        if self.yhsDestLayer:
            self.removeLayer(self.yhsDestLayer)
            self.yhsDestLayer = None
            self.yhsDestLayerSetup = False
        return

    def closeEvent(self, event: QCloseEvent):
        self.closeRotLayer()
        self.closeYhsLayer()
        self.clearData()
        return

