# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PnwRotPyDialog
                                 A QGIS plugin
 Exploration of effect of NW rotation on YHS path
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Steve White
        email                : stevewh@uw.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis._core import QgsMessageLog, Qgis, QgsProject, QgsVectorLayer, QgsPoint, QgsGeometry, QgsFeature
from qgis.PyQt.QtGui import QColor, QCloseEvent # Bug - Qgis is fine with this import, PyCharm is not
from qgis.utils import iface

from .rot_data import RotData
from .plate_motion import PlateMotion, PState

# Important constants
NA_Speed = 3.8e-2   # m / yr
NA_Bearing = 225.0  # degrees azimuth
YHS_lat = 44.43
YHS_long = -110.67

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'pnw_rotation_py_dialog_base.ui'))

class PnwRotPyDialog(QtWidgets.QDialog, FORM_CLASS):
    name = 'PnwRotPyDialog'
    destRotDataLayerName = 'pnw rotation data'
    YHS_lat = 44.43
    YHS_lon = -110.67
    destYhsLayerName = 'YHS movement'

    def __init__(self, parent=None):
        """Constructor."""
        super(PnwRotPyDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.rotData = RotData()
        self.rotDisplayLayerSetup = False
        self.rotDestLayer = None

        self.yhsDestLayerSetup = False
        self.yhsDestLayer = None
        self.yhsPoints = []
        self.plateMotion = PlateMotion()
        self.clearData()
        
        self.clearDataButton.clicked.connect(self.clearData)
        self.displayRotDataButton.clicked.connect(self.displayRotDataButtonClicked)
        self.stepYhsDataButton.clicked.connect(self.stepYhsButtonClicked)

    def clearData(self):
        self.yhsPoints = []
        self.plateMotion.initialize(YHS_lat, YHS_long, NA_Speed, NA_Bearing)
        self.closeYhsLayer()
        self.closeRotLayer() 
        return

    ####
    # Display Rotation Data
    ####

    def displayRotDataButtonClicked(self):
        QgsMessageLog.logMessage('displayRotData', tag=PnwRotPyDialog.name, level=Qgis.Info)

        if not self.setupRotDisplayLayer():
            QgsMessageLog.logMessage('failed to setup display rotation layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        self.displayRotData()
        return True

    def setupRotDisplayLayer(self):
        if self.rotDisplayLayerSetup:
            return True
        if not self.rotData.load():
            QgsMessageLog.logMessage('failed to load rotation data from layer', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        providerName = 'memory'
        uri = 'Point?crs=epsg:4326'
        if self.rotDestLayer is None:
            self.rotDestLayer = QgsVectorLayer(uri, PnwRotPyDialog.destRotDataLayerName, providerName)

        if not self.rotDestLayer.isValid():
            QgsMessageLog.logMessage("Couldn't create rotDestLayer", tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        #Copy over symbology from rot data layer
        sourceRenderer = self.rotData.rotSourceLayer.renderer()
        if not sourceRenderer is None:
            clonedRenderer = sourceRenderer.clone()
            if not clonedRenderer is None:
                self.rotDestLayer.setRenderer(clonedRenderer)

        #Copy rot data fields over too
        if self.rotDestLayer.dataProvider().addAttributes(self.rotData.rotFieldList):
            self.rotDestLayer.updateFields()
        else:
            QgsMessageLog.logMessage('failed to copy rot data', tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        self.rotDisplayLayerSetup = True
        return True

    def displayRotData(self):
        #copy rot data over
        self.rotDestLayer.dataProvider().addFeatures(self.rotData.rotFeatureList)
        QgsProject.instance().addMapLayer(self.rotDestLayer)
        self.rotDestLayer.triggerRepaint()
        return True

    ####
    # run Yhs Button
    ####

    def stepYhsButtonClicked(self):
        QgsMessageLog.logMessage('run Yhs Button Clicked', tag=PnwRotPyDialog.name, level=Qgis.Info)

        if not self.setupYhsLayer() :
            QgsMessageLog.logMessage('failed to setup display rotation layer', tag=PnwRotPyDialog.name, level=Qgis.Info)

        deltaT = float(self.sbStepMy.value()) * 1e6;
        currentState = self.plateMotion.getNextState(deltaT, self.rotData,
                                                     self.rbApplyNARotV.isChecked(), self.rbApplyNaPlateV.isChecked())
        self.yhsPoints.append(QgsPoint(currentState.longitude, currentState.latitude))
        self.displayYhsData()
        return

    def setupYhsLayer(self) :    # Rot layer must be loaded in qgism first(so not at qgis launch)
        if self.yhsDestLayerSetup:
            return True

        QgsMessageLog.logMessage("Setup YHS layer ", tag=PnwRotPyDialog.name, level=Qgis.Info)

        providerName = "memory"    # Or "ogr" for file - based data
        uri = "LineString?crs=epsg:4326" # Example URI for memory provider

        if self.yhsDestLayer is None:
            self.yhsDestLayer = QgsVectorLayer("LineString?crs=EPSG:4326", PnwRotPyDialog.destYhsLayerName, "memory");
        if not self.yhsDestLayer.isValid():
            QgsMessageLog.logMessage("Could not instantiate plugin target layer", tag=PnwRotPyDialog.name, level=Qgis.Info)
            return False

        renderer = self.yhsDestLayer.renderer()
        lineSymbol = renderer.symbol()
        lineSymbol.setWidth(0.5)
        lineSymbol.setColor(QColor(255, 0, 0))
        self.yhsPoints.append(QgsPoint(self.YHS_lon, self.YHS_lat)) # Set initial point to current YHS
        self.yhsDestLayerSetup = True

        return True

    def displayYhsData(self):

        #print("self.yhsPoints: ", self.yhsPoints)

        #copy yhs data over
        feature = QgsFeature(self.yhsDestLayer.fields())
        feature.setGeometry(QgsGeometry.fromPolyline(self.yhsPoints))

        # Add feature to layer
        self.yhsDestLayer.startEditing()
        self.yhsDestLayer.addFeature(feature)
        self.yhsDestLayer.commitChanges()
        QgsProject.instance().addMapLayer(self.yhsDestLayer)

        self.yhsDestLayer.triggerRepaint()
        return True

    def removeLayer(self, layer):
        if layer :
            root = QgsProject.instance().layerTreeRoot()
            layer_node = root.findLayer(layer.id())
            if layer_node:
                layer_node.setItemVisibilityChecked(False)  # Set the checkbox to unchecked
                QgsProject.instance().removeMapLayers([layer.id()])
                iface.mapCanvas().refresh()
        return

    def closeRotLayer(self):
        if self.rotDestLayer:
            self.removeLayer(self.rotDestLayer)
            self.rotDestLayer = None
            self.rotDisplayLayerSetup = False

    def closeYhsLayer(self):
        if self.yhsDestLayer:
            self.removeLayer(self.yhsDestLayer)
            self.yhsDestLayer = None
            self.yhsDestLayerSetup = False

    def closeEvent(self, event: QCloseEvent):
        self.closeRotLayer()
        self.closeYhsLayer()

           # self.plateMotion = None
        return

